import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// One sidebar entry per generated Part page (see whitepaperSplit.ts). Order and
// labels come from each page's sidebar_position / sidebar_label frontmatter.
const sidebars: SidebarsConfig = {
  whitepaperSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
